<h5>When you are ready, click the microphone button and start reading out loud. When you are done, click on the microphone button to stop recording, and submit your recording.</h5>
<p><strong>Please record the following as part of your reading of the story: this allows us to coordinate readings with locations.</strong>  “My name is _____(your full name)_____ and I live in _____(your current home location)_____. This is my reading of <strong>Vancouver Dawn</strong>.”</p>
<h2 style="text-align: center;"><strong>Vancouver Dawn</strong></h2>
<p>Mike rolled out of his cot, glanced over at Danny sleeping on the floor, and then staggered down the hall to the kitchen. His head was still thick from last night’s beer. The sink had bits of pasta and eggshell in it, and part of an old bagel. Dumping a tin of beans in a pan to heat, he rolled a cigarette, then stared out the window. Grey February lightened the peaks above Vancouver and a vee of Canada geese drifted high above the neighbour’s roof. The crow was back on the telephone pole across the street, silhouetted against a mountain.</p>
<p>Last night he made a phone call to Verna to ask for more money. He hated to do that but things were pretty thin right now. She could be such a drama queen. Angry. Rude. So negative, always saying he was the root of the problem. She wanted him to beg her to come back. It had taken a few beers to get over that conversation. When he ran into her at the plaza on Tuesday he had to pull his hat down tight and walk away while she yelled that he was a sorry excuse for a father. As if she was a good mom! She liked to bait him. She would brag about the salmon bakes around the pool at Frank’s new house, about the thick oak beams in the living room, about the holidays. He wasn’t sure if he had the strength to face her again, let alone try to talk things out. He might have to change the route he walked.</p>
<p>Danny appeared in the kitchen doorway, still in his pajamas. “Hey pal, we’re up! How’s my buddy, how’s it going, eh?” Mike said. He said that every morning. And every morning Danny would look at the floor and shrug. Mike pushed bread into the toaster. When it was done he dumped beans on the toast, poured some milk, and slid them in front of Danny. Danny picked up a pen and began scribbling, his head bent low over some scrap paper. He always drew animals. Moose, bears, skunks, mice, ducks, eagles, kittens, goats. But not people. Never people. Sometimes the animals would be missing a paw or a hoof. He once drew a mouse missing a leg. Mike hated that drawing.</p>
<p>Mike went back to the window, nursing his cigarette and wishing for a coffee. He listened to the scratching of Danny’s pen, the muttering of the radio news, and the quiet tick-tock of the hall clock. He took another drag on his cigarette and said, “Eat up, buddy.” Like he did every morning. Who’d have thought a regular job could disappear so quickly? Ten years down in the hole, pulling out ton after ton of ore, a decent paycheck up at the mine, lots of laughs with Verna, it had been a good life. Then bang! Gone.</p>
<p>He heard Danny slide out of the kitchen and go back to the bedroom to change, a half bitten piece of toast left on his plate. Mike opened his mouth to speak, then thought better of it. After the accident, things had gone south: the dance of endless Workers Comp meetings, the lag between promises and payments, a constant sore back, the metal pin a pain in his leg. And Verna always a pain in his neck.</p>
<p>It was time to go. He sighed, stubbed out his cigarette, dumped things in the sink to wash later, and helped Danny into his boots and raincoat. Danny picked up his school bag and they headed out together into the Vancouver dawn.</p>
<p>© 2017/18 B. Pritchard</p>
<p><h5>Thank you for recording yourself reading this passage! You can now click the microphone icon to stop recording. Please submit your recording using the "Submit Recording" button.</h5></p>
<p><h5>A successful submission should result in the message "Upload Successful!" displayed below the recorder. After seeing this message, you may close your web browser. Thank you for your participation in this project!</h5></p>
