<option value='Canadian English'>Canadian English</option>
<option value='Canadian French'>Canadian French</option>
<option value='First Nations'>First Nations</option>
<option value='American (US) English'>American (US) English</option>
<option value='Arabic'>Arabic</option>
<option value='Awadhi'>Awadhi</option>
<option value='Azerbaijani, North'>Azerbaijani, North</option>
<option value='Azerbaijani, South'>Azerbaijani, South</option>
<option value='Bengali'>Bengali</option>
<option value='Bhojpuri'>Bhojpuri</option>
<option value='Burmese'>Burmese</option>
<option value='Chinese, Gan'>Chinese, Gan</option>
<option value='Chinese, Hakka'>Chinese, Hakka</option>
<option value='Chinese, Jinyu'>Chinese, Jinyu</option>
<option value='Chinese, Mandarin'>Chinese, Mandarin</option>
<option value='Chinese, MinNan'>Chinese, MinNan</option>
<option value='Chinese, Wu'>Chinese, Wu</option>
<option value='Chinese, Xiang'>Chinese, Xiang</option>
<option value='Chinese, Yue (Cantonese)'>Chinese, Yue (Cantonese)</option>
<option value='Dutch'>Dutch</option>
<option value='English'>English</option>
<option value='French'>French</option>
<option value='German'>German</option>
<option value='Gujarati'>Gujarati</option>
<option value='Hausa'>Hausa</option>
<option value='Hindi'>Hindi</option>
<option value='Italian'>Italian</option>
<option value='Japanese'>Japanese</option>
<option value='Javanese'>Javanese</option>
<option value='Kannada'>Kannada</option>
<option value='Korean'>Korean</option>
<option value='Maithili'>Maithili</option>
<option value='Malayalam'>Malayalam</option>
<option value='Marathi'>Marathi</option>
<option value='Oriya'>Oriya</option>
<option value='Panjabi, Eastern'>Panjabi, Eastern</option>
<option value='Panjabi, Western'>Panjabi, Western</option>
<option value='Persian'>Persian</option>
<option value='Polish'>Polish</option>
<option value='Portuguese'>Portuguese</option>
<option value='Romanian'>Romanian</option>
<option value='Russian'>Russian</option>
<option value='Serbo-Croatian'>Serbo-Croatian</option>
<option value='Sindhi'>Sindhi</option>
<option value='Spanish'>Spanish</option>
<option value='Sunda'>Sunda</option>
<option value='Tamil'>Tamil</option>
<option value='Teluga'>Teluga</option>
<option value='Thai'>Thai</option>
<option value='Turkish'>Turkish</option>
<option value='Ukrainian'>Ukrainian</option>
<option value='Urdu'>Urdu</option>
<option value='Vietnamese'>Vietnamese</option>
<option value='Yoruba'>Yoruba</option>
<option value='Other'>Other</option>